---
title: "orion_paper"
output: html_document
date: "2023-08-18"
---

```{r setup, include=FALSE}
library(data.table)
library(tidyr)  # For gather()
library(tidyverse)
library(ggplot2)
library(survival)
library(forestplot)
library(survminer)
source("~/git/cysift/R/helpers.R")
source("~/Sorger/projects/orion/R/orion_helpers.R")

generate_random_string <- function(string_length = 8) {
  characters <- c(letters, LETTERS, 0:9)  # alphanumeric characters
  random_string <- paste0(sample(characters, string_length, replace = TRUE), collapse = "")
  return(random_string)
}
```

```{r load-data, include=FALSE}
# load clinical data
load_redcap()

# re-format pMMR into factor
redcap$pMMR <- factor(redcap$pMMR, levels = c(0, 1), labels = c("dMMR", "pMMR"))

# Verify the transformation
table(redcap$pMMR)

## DUMMY data for the unknown grade data
redcap[Grade == "Unknown", Grade := "Low"]
redcap$Grade <- factor(redcap$Grade, levels = c("Low", "High"))

# setup other clinical/histological adta
redcap[, mucinous := as.factor(ifelse(grepl("ucinous", Histology), 1, 0))]
redcap$Location <- factor(redcap$Location, levels = c("Appendix", "Cecum", "Ascending", "Transverse", "Descending", "Sigmoid", "Rectosigmoid", "Rectum"))

# anatomic location
redcap[, side := {
  if (Location %in% c("Appendix","Cecum","Ascending","Transverse")) {
    "Right"
  } else if (Location %in% c("Sigmoid","Descending")) {
    "Left"
  } else {
    "Rectal"
  }
}, by="Slide_ID"]
```

```{r plot-setup-stuff, include=FALSE}
# ggplot theme
theme_jw <- function() {
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text = element_text(color = "black")
  )
}

# color theme
pMMR_colors <- c("dMMR" = "#fdc086", "pMMR" = "#5ab4ac", "tipMMR"="#beaed4")

# plot to pdf function
save_pdf <- function(g, filename, width=10, height=10) {
  filepath <- paste0("~/Sorger/projects/orion/figs_raw_paper/", filename)
  
  pdf(filepath, useDingbats = FALSE, width, height)
  print(g)
  dev.off()
}
```

```{r cys-read, include=FALSE}
if (FALSE) {
  files <- list.files(path = "~/Sorger/projects/orion/orion_1_74/margin/", full.names = TRUE)
  files <- files[grepl("cys$", files)]
  
  header <- header_read(files[1])
  # read all the data as the means within the tumor compartment
  dtt <- lapply(files, function(f) {
    cat(basename(f), "\n")
    fv = "-A 5 -T"
    tmpfile <- paste0("/tmp/", generate_random_string(8))

    system(paste("cysift filter", fv, f, tmpfile))
    dt <- fread(cmd=paste("cysift mean", tmpfile, " - | cysift view -"))
    
    setnames(dt, paste0("V",seq(6)), c("sample","cell","x","y","pflag","cflag"))
    setnames(dt, paste0("V",seq(7,ncol(dt))), header$id[header$tag_type %in% c("CA","MA")])
    
    dt[ , allcount       := fread(cmd=paste("cysift count", tmpfile))$V1]

    # indivdual cell counts
    drr = fread(cmd=paste("cysift cellcount", tmpfile," - -a 133120 -a 10240 -a 36864 -a 32832 -a 0 | cysift view -"))
    dt[, cd31count := drr$V28]
    dt[, cd45count := drr$V29]
    dt[, cd68count := drr$V30]
    dt[ ,cd4count. := drr$V32]
    dt[, foxp3count:= drr$V33]
    dt[, cd8count  := drr$V34]
    dt[, cd45rocount  := drr$V35]
    dt[, cd20count := drr$V36]
    dt[, pdl1count := drr$V37]
    dt[, cd3count := drr$V38]
    dt[, cd163count := drr$V39]
    dt[, pd1count := drr$V41]
    dt[, panckcount := drr$V43]
    dt[, smacount := drr$V44]
    dt[ , pdl1panckcount := drr$V45]
    dt[ , pdl1cd163count := drr$V46]
    dt[ , cd3pd1count    := drr$V47]
    dt[ , cd4pd1count    := drr$V48]
    
    ## radial means
    tmpfile2 <- paste0("/tmp/", generate_random_string(8))

    drr <- fread(cmd=paste("cysift filter -a 131072", tmpfile, tmpfile2, "&& cysift mean", tmpfile2, "-",
                           "| cysift view -"))
    file.remove(tmpfile2)
    
    dt[, panckcd3_20r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD3_20r") + 6)]]]
    dt[, panckcd4_20r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD4_20r") + 6)]]]
    dt[, panckcd8_20r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD8_20r") + 6)]]]
    dt[, panckcd3_200r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD3_200r") + 6)]]]
    dt[, panckcd4_200r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD4_200r") + 6)]]]
    dt[, panckcd8_200r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD8_200r") + 6)]]]
    dt[, panckcd163pdl1_200r  := drr[[paste0("V",which(header$id[header$tag_type %in% c("CA","MA")] == "CD163pPDL1_200r") + 6)]]]
    
    dt[, Slide_ID := sub("^(LSP[0-9]+).*", "\\1", basename(f))]
    dt[, margin := "tumor_margin"]
    file.remove(tmpfile)
    return(dt)
  })
  
  dtr <- rbindlist(dtt)
  rr <- merge(data.table::copy(redcap), dtr, by = "Slide_ID", all.x = TRUE)
  saveRDS(dtr, "~/Sorger/cache/tumor_margin_Oct24.rds", compress=FALSE)
} else {
  
  #dtr <- rbindlist(lapply(c("~/Sorger/cache/margin5.rds",
  #                       "~/Sorger/cache/margin4.rds",
  #                       "~/Sorger/cache/stroma_n5.rds",
  #                       "~/Sorger/cache/core1.rds"), readRDS))
  dtr <- rbindlist(lapply(c("~/Sorger/cache/margin_A4_Oct24.rds",
                            "~/Sorger/cache/tumor_A1_Oct24.rds",
                            "~/Sorger/cache/stroma_N5_Oct24.rds",
                            "~/Sorger/cache/tumor_margin_Oct24.rds",
                            "~/Sorger/cache/stroma_margin_Oct24.rds"), readRDS))
  rr <- merge(data.table::copy(redcap), dtr, by = "Slide_ID", all.x = TRUE)
  hard_coded_tip <- c("LSP14418", "LSP14398", "LSP14423", "LSP14438", "LSP14393", "LSP14403", "LSP14458", "LSP10771", "LSP14388", "LSP14468", "LSP14483", "LSP10388", "LSP14448")
  hard_coded_tip_core = c("LSP14468", "LSP14448", "LSP14403", "LSP15280","LSP14418","LSP14438","LSP10388","LSP14388")
  rr[, tipMMR := factor(ifelse(Slide_ID %in% hard_coded_tip, ifelse(pMMR=="dMMR","dMMR","tipMMR"), as.character(pMMR)))]
}
```

```{r x-y-plot}

rr_melt <- melt(rr, id.vars=c("Slide_ID", "margin", "allcount"), measure.vars=c("cd3count","cd8count"))

g <- ggplot(rr_melt[variable=="cd3count"], aes(x=Slide_ID, y=value / allcount)) + 
  geom_bar(aes(fill = margin), stat="identity", position='dodge') +
  #geom_text_repel(aes(label = Slide_ID)) +
  theme_jw()

t.test(rr[margin=="tumor_A1", cd3count/allcount], rr[margin=="margin_A4", cd3count/allcount], paired=TRUE)

rr_reshaped <- dcast(rr, Slide_ID ~ margin, value.var = c("cd3count", "allcount"))
rr_reshaped[, `:=`(
  tumor_ratio = cd3count_tumor_A1/allcount_tumor_A1,
  margin_ratio = cd3count_margin_A4/allcount_margin_A4,
  stroma_ratio = cd3count_stroma_N5/allcount_stroma_N5,
  stroma_margin_ratio = cd3count_stroma_margin/allcount_stroma_margin,
  tumor_margin_ratio = cd3count_tumor_margin/allcount_tumor_margin

)]
p.val = t.test(rr[margin=="tumor_margin", cd3count/allcount], rr[margin=="tumor_A1",cd3count/allcount])$p.value
g <- ggplot(rr_reshaped, aes(x = tumor_ratio, y = tumor_margin_ratio, label = Slide_ID)) +
  geom_point( size = 1) +
    geom_abline(intercept = 0, slope = 1, linetype="dotted", color="red", linewidth=1) +  # adding the x=y line
  #geom_text_repel(aes(label = Slide_ID), nudge_y = 0.05, nudge_x = 0.05) +
  theme_minimal() +
  scale_x_log10() + scale_y_log10() + ggtitle(paste("p=",p.val)) + 
  labs(x = "Tumor cd3count/allcount", y = "Tumor Margin cd3count/allcount")

save_pdf(g , "tumor_v_tumormargin_cd3.pdf", width=3,height=3)
```

```{r km-plots-imaging}

parm <- "hi"
rd <- data.table::copy(rr[margin=="tumor_A1"])
med <- rd[, median(panckcd3_200r)]
rd[, hi := ifelse(panckcd3_200r > med, "hi","lo")]
pfs <- TRUE; s <- rep(pfs, nrow(rd))
rd[, PFSC := ifelse(rd$PFSCensor==0,1,0)]
surv_model <- Surv(ifelse(s, rd$PFSDays, rd$OSDays), 
                       ifelse(s, ifelse(rd$PFSCensor==0,1,0),ifelse(rd$OSCensor ==0,1,0)))
model_fit = survfit(surv_model ~ get(parm), data = rd)

dt.plot <- data.table(time=model_fit$time, 
                        surv=model_fit$surv,
                        strata=as.vector(unlist(sapply(names(model_fit$strata), function(x) rep(x, model_fit$strata[x])))),
                        lower=model_fit$lower, upper=model_fit$upper, censor=model_fit$n.censor)
  dt.plot[, strata := gsub("get\\(parm\\)=", "", strata)]
  dt.1 <- dt.plot[!duplicated(strata)]; dt.1$time=1; dt.1$surv=1; dt.1$lower=1; dt.1$upper=1; dt.1$censor=0
  dt.plot <- rbind(dt.plot, dt.1)
  
  # # Fit a Cox proportional hazards model to the data
  cox_model <- coxph(surv_model ~ get(parm), data = rd)
  
  # get the HRF
  coefs <- -coef(cox_model)

  se <- sqrt(diag(vcov(cox_model)))
  hr <- list(hr=exp(coefs), lower=exp(coefs - 1.96 * se), 
             upper=exp(coefs + 1.96 * se))
  hr.lab <- paste0("HR: ", round(hr[[1]], 3), " [", round(hr[[2]], 2),"-", round(hr[[3]], 2), "]")
  hr.x <- max(dt.plot$time)*0.9
  hr.y <- max(dt.plot$surv)*0.9
 
  # plot the K-M curves
  g <- ggplot(dt.plot[time < 2400], aes(x = time/365, y = surv, color = strata)) +
    geom_ribbon(aes(ymin = lower,ymax = upper, fill=strata),alpha = 0.15, linetype=0) +
    geom_step(aes(color=strata), size=1) +
    geom_point(data = dt.plot[censor == 1][time < 2400], aes(x=time/365,y=surv), shape="+", size=3, color="black") + 
    labs(x = "\nYears", y = ifelse(pfs,"Progression-Free Survival","Overall Survival\n")) + theme_bw() + 
    ggtitle(hr.lab) + 
    #scale_color_manual(name=parm.name,values=parm.vals,labels=parm.labels) + 
    scale_x_continuous(breaks=s<-seq(0,6), labels=s) + 
    #scale_fill_manual(values=parm.vals, guide="none") + 
    #annotate("text", x = hr.x, y = hr.y,label=hr.lab,hjust = 1, vjust = 1) + 
    scale_y_continuous(limits=c(0,1), breaks= s<-seq(0, 1, by = 0.2), labels = s) +
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), 
          legend.position = "none")
save_pdf(g, "panck_cd8_20r_km_tumor.pdf", 3,3)
  
```

```{r mark-the-tipMMR, include=FALSE}
if (FALSE) {
  hard_coded_tip <- c("LSP14418", "LSP14398", "LSP14423", "LSP14438", "LSP14393", "LSP14403", "LSP14458", "LSP10771", "LSP14388", "LSP14468", "LSP14483", "LSP10388", "LSP14448")
  rr[, tipMMR := factor(ifelse(Slide_ID %in% hard_coded_tip, ifelse(pMMR=="dMMR","dMMR","tipMMR"), as.character(pMMR)))]
} else if (FALSE) {
  
  #### MARK THE TIPMMR BY CD3
  # Slide LSP10716 is the 8/9 ranked by CD3
  rr[, tipMMR := factor(ifelse(CD3_200r > rr[Slide_ID=="LSP10716", CD3_200r], ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
  rr$tipMMR <- factor(rr$tipMMR, levels = c("pMMR", "tipMMR", "dMMR"))
  g <- km_plot(rr[pMMR=="pMMR"], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE)
  table(rr$tipMMR)
  rr[tipMMR=="tipMMR", Slide_ID]
} else {
  
  #### MARK THE TIPMMR BY CD8
  # Slide LSP10716 is the 23rd percetile of dMMR
  if (FALSE) {
    rr[, tipMMR := factor(ifelse(CD8_200r > rr[Slide_ID=="LSP10716", CD8_200r], ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
    g <- km_plot(rr[pMMR=="pMMR"], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE)
    table(rr$tipMMR)
    rr[tipMMR=="tipMMR", Slide_ID]
  }
}

```


```{r imaging-km}
rr <- merge(data.table::copy(redcap), dtr[margin=="tumor_A1"], by = "Slide_ID", all.x = TRUE)
ix <- rep(TRUE, nrow(rr))
rr[, PFSC := ifelse(rr$PFSCensor==0,1,0)]
survival_object <- Surv(rr$PFSDays[ix], rr$PFSC)

all_200r <- c("CD31_200r","CD45_200r","CD68_200r","CD4_200r",
                   "FOXP3_200r","CD8_200r","CD45RO_200r","CD20_200r",
                   "PD_L1_200r","CD3_200r","CD163_200r","Ecad_200r",
                  "PD1_200r","Ki67_200r","PanCK_200r","SMA_200r")
all_200g <- c("CD31_200g","CD45_200g","CD68_200g","CD4_200g",
                   "FOXP3_200g","CD8_200g","CD45RO_200g","CD20_200g",
                   "PD_L1_200g","CD3_200g","CD163_200g","Ecad_200g",
                  "PD1_200g","Ki67_200g","PanCK_200g","SMA_200g")
all_200gl <- c("CD31_200gl","CD45_200gl","CD68_200gl","CD4_200gl",
                   "FOXP3_200gl","CD8_200gl","CD45RO_200gl","CD20_200gl",
                   "PD_L1_200gl","CD3_200gl","CD163_200gl","Ecad_200gl",
                  "PD1_200gl","Ki67_200gl","PanCK_200gl","SMA_200gl")

all_hr <- lapply(all_200r, function(x) {
  label = x;
  res.cut <- survminer::surv_cutpoint(rr[ix], time = "PFSDays", event = "PFSC", variables = label)

   #                 x = "rand"
  #rr[, rand := sample(1000, .N)]
  median_cut <- median(rr[[x]][ix])
  cox_model <- coxph(survival_object ~ rr[[x]][ix] >= res.cut$cutpoint$cutpoint)
cat(x, "\n")
  # Extract the coefficients from the Cox model
  coefficients <- cox_model$coefficients
  hr <- exp(coefficients)
  hr <- data.table(
    variable = names(coefficients),
    HR = hr,
    lower = exp(as.data.table(confint(cox_model, level = 0.95))$`2.5 %`),
    upper = exp(as.data.table(confint(cox_model, level = 0.95))$`97.5 %`)
  )
  hr$variable <- factor(hr$variable, levels = hr$variable[order(-hr$HR)])
  hr$label = label
  return(hr)
                  })
hr <- rbindlist(all_hr)
# Create the forest plot
g <- ggplot(
  data = hr,
  aes(x = label, y = HR, ymin = lower, ymax = upper)) +
  geom_pointrange(size = 0.8) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  coord_flip() +
  xlab("Covariate") +
  ylab("Hazard Ratio") +
  theme_jw()

```

```{r plot-tippness}

```


```{r random-hr-tip, include=FALSE}

## get distribution of HR for "random" tipMMR, selected from pMMR
# set.seed(42)
# rrpmmr <- rr[pMMR == "pMMR"]
# hrdist <- sapply(seq(5000), function(cc) {
#   if (cc %% 100 == 0)
#     cat(cc,"\n")
#   rrpmmr[, rand_label := "hi"]
#   rrpmmr[sample(.N, 13), rand_label := "low"]
#   hr <- as.numeric(km_plot(rrpmmr, parm="rand_label", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE, return.model=TRUE)$hr[1])
#   return(hr)
# })
# saveRDS(hrdist, "~/Sorger/cache/hrdist.rds")
hrdist <- readRDS("~/Sorger/cache/hrdist.rds")

# plot random distribution of hazard ratios vs tipMMR
g <- ggplot(data.table(hr=hrdist[hrdist < 10]), aes(x=hr)) + geom_histogram(stat="bin", binwidth=0.05) + 
  theme_jw() + xlab("Hazard Ratio") + ylab("Frequency") + geom_vline(aes(xintercept=1), color="red") +
 geom_vline(aes(xintercept=0.09), color="blue")
save_pdf(g, "cd3_tipmmr_random.pdf", width=3, height=2)

## iteratively search for best HR
# hrs.cd3 <- rbindlist(lapply(sort(rr$CD3_200r)[seq(5,nrow(rr)-5)], function(cc) {
#   rr[, tipMMR := factor(ifelse(CD3_200r > cc, ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
#   cat(cc, "\n")
#   return(data.table(cutoff=cc, hr=as.numeric(km_plot(rr[pMMR=="pMMR"&PFSDays > 0], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE, return.model=TRUE)$hr[1]), numtip = table(rr$tipMMR)["tipMMR"], cell="CD3"))
# }))
# hrs.cd8 <- rbindlist(lapply(sort(rr$CD8_200r)[seq(5,nrow(rr)-5)], function(cc) {
#   rr[, tipMMR := factor(ifelse(CD8_200r > cc, ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
#   return(data.table(cutoff=cc, hr=as.numeric(km_plot(rr[pMMR=="pMMR"&PFSDays > 0], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE, return.model=TRUE)$hr[1]), numtip = table(rr$tipMMR)["tipMMR"], cell="CD8"))
# }))
# hrs.cd8 <- rbindlist(lapply(sort(rr$CD8_200r)[seq(5,nrow(rr)-5)], function(cc) {
#   rr[, tipMMR := factor(ifelse(CD8_200r > cc, ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
#   return(data.table(cutoff=cc, hr=as.numeric(km_plot(rr[pMMR=="pMMR"&PFSDays > 0], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE, return.model=TRUE)$hr[1]), numtip = table(rr$tipMMR)["tipMMR"], cell="CD8"))
# }))
# hrs.rand <- rbindlist(lapply(sort(rr$rand)[seq(5,nrow(rr)-5)], function(cc) {
#   rr[, tipMMR := factor(ifelse(rand > cc, ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
#   return(data.table(cutoff=cc, hr=as.numeric(km_plot(rr[pMMR=="pMMR"&PFSDays > 0], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE, return.model=TRUE)$hr[1]), numtip = table(rr$tipMMR)["tipMMR"], cell="rand"))
# }))
# hrs <- rbind(hrs.cd3, hrs.cd8, hrs.rand)
# 
# rr[, tipMMR := factor(ifelse(CD8_200r > 50, ifelse(pMMR == "dMMR", "dMMR", "tipMMR"), as.character(pMMR)))]
# km_plot(rr[pMMR=="pMMR" & PFSDays > 90], parm="tipMMR", parm.name="tipMMR",parm.labels=c(tipMMR="tipMMR",pMMR="pMMR"), flip=TRUE, flip.labels=TRUE, pfs=TRUE)
# 
# # plot of HR by number of samples designated as tipMMR
# g <- ggplot(hrs, aes(x=numtip, y=hr, color=cell)) + geom_point() + theme_jw()
```



```{r neoadjuvant}
redcap[grepl("y",TNM_At_Diagnosis), Location]
table(grepl("y", redcap$TNM_At_Diagnosis))
```

```{r clinical-figures}

# grade - pMMR vs tipMMR
g <- ggplot(redcap, aes(x = Grade, fill = pMMR, group=pMMR)) +
  geom_bar(color="black") +
  labs(x = "Histological grade",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "grade_bar.pdf", width=3, height=3)

# grade - with tipMMR
g <- ggplot(rr, aes(x = Grade, fill = tipMMR, group=tipMMR)) +
  geom_bar(color="black") +
  labs(x = "Histological grade",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "grade_bar.pdf", width=3, height=3)

# Gender
g <- ggplot(redcap, aes(x = Gender, fill = pMMR, group=pMMR)) +
  geom_bar(color="black") +
  labs(x = "Gender",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "gender_bar.pdf", width=2, height=3)

# Gender with tipMMR
g <- ggplot(rr, aes(x = Gender, fill = tipMMR, group=tipMMR)) +
  geom_bar(color="black", position="dodge") +
  labs(x = "Gender",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "gender_bar_tipMMR.pdf", width=2, height=3)

# location
g <- ggplot(redcap, aes(x = Location, fill = pMMR, group=pMMR)) +
  geom_bar(color="black") +
  labs(x = "Anatomical location",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "location_bar.pdf", width=6, height=3)

# location with tipMMR
rr_complete <- as.data.table(tidyr::complete(rr, Location, tipMMR, fill = list(n = 0)))
rr_complete[, count := sum(!is.na(Slide_ID)), by=c("tipMMR","Location")]
g <- ggplot(rr_complete, aes(x = Location, fill = tipMMR, group=tipMMR)) +
  geom_bar(aes(y=count), color="black", position="dodge", stat="identity") +
  labs(x = "Anatomical location",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "location_bar_tipmmr.pdf", width=6, height=3)

# stage
g <- ggplot(redcap, aes(x = Stage_At_Diagnosis, fill = pMMR, group=pMMR)) +
  geom_bar(color="black") +
  labs(x = "Stage at diagnosis",
       y = "Count") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw()
save_pdf(g, "stage_bar.pdf", width=3, height=3)

# age
g <- ggplot(redcap, aes(x = pMMR, y = Age, fill = pMMR)) +
  geom_boxplot(alpha = 1, width=0.8, outlier.shape=NA) + 
  geom_jitter(position = position_jitter(width = 0.2), size = 3, alpha = 1, shape=20) +  
  labs(y = "Age") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "age_box.pdf", width=3, height=3)

```

```{r mutations}

# reshape the mutation data
long_data <- rr %>%
  gather(key = "Mutation", value = "Status", APC, p53, KRAS, BRAF, PIK3CA, SOX9, FBXW7, TCF7L2, CTNNB1, PTEN, NRAS) %>%
  filter(Status == 1)  # Keep only mutated entries

# Compute the total count for each mutation
mutation_counts <- long_data %>%
  group_by(Mutation) %>%
  summarize(Total = n())
long_data$Mutation <- factor(long_data$Mutation, levels = rev(mutation_counts$Mutation[order(-mutation_counts$Total)]))

# Bar chart of mutation counts
g <- ggplot(long_data, aes(x = Mutation, fill = as.factor(pMMR))) +
  geom_bar(color="black") +  # Stacked bar chart
  coord_flip() +  # Make the bar chart horizontal
  labs(title = "Mutation Counts by pMMR Status",
       x = "Mutation",
       y = "Count") +
  theme_jw() + 
  scale_fill_manual(values = pMMR_colors, name = "MMR status")

# KM curves by mutation
g <- lapply(c("APC","p53","KRAS","BRAF","PIK3CA"), function(x) {
 km_plot(redcap, x, x, c("0"="WT", "1"="Mutated"), pfs=TRUE)
})

# Known HRs by effect
known <- data.table()
#known <- rbind(known, data.table(variable="PIK3CA", hr=1.20, lower=0.98, upper=1.46, pmid="27436848", type="PFS", note=""))
known <- rbind(known, data.table(variable="PIK3CA", hr=0.96, lower=0.83, upper=1.12, pmid="27436848", type="OS", note=""))
known <- rbind(known, data.table(variable="APC", hr=0.62, lower=0.44, upper=0.83, pmid="33230914", type="OS", note="pMMR only"))
known <- rbind(known, data.table(variable="BRAF", hr=2.25, lower=1.82, upper=2.83, pmid="34843402", type="OS", note=""))
known <- rbind(known, data.table(variable="LVI", hr=2.37, lower=0.95, upper=5.89, pmid="24886281", type="OS", note="Stage III"))
known <- rbind(known, data.table(variable="PNI", hr=0.99, lower=0.14, upper=7.14, pmid="24886281", type="OS", note="Stage III"))
known <- rbind(known, data.table(variable="Grade", hr=1.45, lower=0.72, upper=2.90, pmid="24886281", type="OS", note="Poor differentiation. Stage III"))
known <- rbind(known, data.table(variable="Gender", hr=1.16, lower=0.75, upper=1.80, pmid="24886281", type="OS", note="Male. Stage III"))
known[, source := "lit"]

# HR by mutation
hr <- rbindlist(lapply(nn <- c("APC","p53","KRAS","BRAF","PIK3CA", "LVI","PNI","Grade", "mucinous", "Gender"), function(x) {
 rr <- data.table::copy(redcap)
 flip = FALSE
 if (x == "Grade") {
   rr <- redcap[Grade != "Unknown"]
   flip=TRUE
 }
 dt <- km_plot(rr, x, x, c("0"="WT", "1"="Mutated"), pfs=TRUE, return.model=TRUE, flip=flip)
 return(data.table(hr = dt$hr, lower = dt$lower, upper = dt$upper, variable=x))
}))
hr$variable <- factor(hr$variable, levels = hr$variable[order(-hr$HR)])
hr[, source := "us"]

#plot just our hazard ratios
g <- ggplot(hr, aes(y = variable, x = hr)) +
  geom_point(aes(x = hr), size = 3) +
  geom_errorbarh(aes(xmin = lower, xmax = upper), height = 0.2) +
  labs(x = "Hazard Ratio",
       y = "Gene") +
    geom_vline(aes(xintercept = 1), color = "red", linetype = "dashed") +  # Add vertical red line at HR = 1
  theme_jw()

# Combine our cohort with the literature
combined_data <- rbindlist(list(hr, known), fill = TRUE)
combined_data$variable <- factor(combined_data$variable, levels = hr$variable[order(-hr$hr)])
g <- ggplot(combined_data, aes(y = variable, x = hr, color = source)) +
  geom_point(aes(x = hr), size = 3, position = position_dodge(width = 0.3)) +
  geom_errorbarh(aes(xmin = lower, xmax = upper), height = 0.2, position = position_dodge(width = 0.3)) +
  scale_color_manual(values = c("us" = "black", "lit" = "red")) +
  labs(title = "Hazard Ratios with Confidence Intervals",
       x = "Hazard Ratio",
       y = "Gene") +
  theme_jw() +
      geom_vline(aes(xintercept = 1), color = "black", linetype = "dashed") +  # Add vertical red line at HR = 1
  theme(legend.title = element_blank())
```

```{r tmb}
g <- ggplot(rr[!is.na(tmb)], aes(x = tipMMR, y = tmb, fill = tipMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Mut / Mb") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw()
save_pdf(g, "tmb_with_tipmmr.pdf", width=3, height=3)
```


```{r km-curves}
g <- km_plot(redcap, "pMMR", "pMMR", c("0"="dMMR", "1"="pMMR"), pfs=FALSE, flip=TRUE) + scale_color_manual(values=pMMR_colors) + scale_fill_manual(values=pMMR_colors)
```

```{r plot-tipness}

## read all of the CD3
f <- data.table::fread("~/Sorger/projects/orion/orion_1_74/cut/tumor_cd3_200r")
f[, type := "T"]
si <- data.table::fread("~/Sorger/projects/orion/orion_1_74/cut/stroma_cd3_200r")
si[, type := "S"]
fsi <- rbind(f, si)
g <- ggplot(fsi[sample(.N, 1e5)], aes(x=V1, fill=type)) + 
  geom_histogram(position="dodge", binwidth=30) + 
  theme_jw()
tt <- ecdf(f$V1)
mm_tumor <- median(f$V1)

#system("cysift subsample -r 0.1 ~/Sorger/projects/orion/orion_1_74/margin/LSP10353.ptrdim.cys - | cysift view - > /tmp/tmpr", intern=TRUE)
dt <- data.table::fread("/tmp/tmpr")
header <- header_read("~/Sorger/projects/orion/orion_1_74/margin/LSP10353.ptrdim.cys")
setnames(dt, paste0("V",seq(6)), c("sample","cell","cflag","pflag","x","y"))
setnames(dt, paste0("V",seq(7,ncol(dt))), header$id[header$tag_type %in% c("CA","MA")])
dt[CD3_200r > 5000, CD3_200r := 5000]
g <- ggplot(dt, aes(x=x, y=y, color=CD3_200r)) + theme_jw() + geom_point() + 
   scale_color_gradient2(low = "blue", mid = "white", high = "red", 
                        midpoint = mm_tumor) + coord_fixed()
```

```{r cox-ph-no-imaging-no-molecular}
ix <- rep(TRUE, nrow(redcap))
survival_object <- Surv(redcap$PFSDays[ix], ifelse(redcap$PFSCensor[ix]==0,1,0))
cox_model <- coxph(survival_object ~ redcap$Gender[ix] + redcap$mucinous[ix] + redcap$Grade[ix] + redcap$LVI[ix] + redcap$PNI[ix] + redcap$stage_num[ix] + redcap$pMMR[ix])

# Extract the coefficients from the Cox model
coefficients <- cox_model$coefficients
hr <- exp(coefficients)
hr <- data.table(
  variable = names(coefficients),
  HR = hr,
  lower = exp(as.data.table(confint(cox_model, level = 0.95))$`2.5 %`),
  upper = exp(as.data.table(confint(cox_model, level = 0.95))$`97.5 %`)
)
hr$variable <- factor(hr$variable, levels = hr$variable[order(-hr$HR)])

# Create the forest plot
g <- ggplot(
  data = hr,
  aes(x = variable, y = HR, ymin = lower, ymax = upper)) +
  geom_pointrange(size = 0.8) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  coord_flip() +
  xlab("Covariate") +
  ylab("Hazard Ratio") +
  theme_jw()
```

```{r cox-ph-no-imaging-with-molecular}
ix <- rep(TRUE, nrow(redcap))
ix <- redcap[, pMMR=="pMMR"]
survival_object <- Surv(redcap$PFSDays[ix], ifelse(redcap$PFSCensor[ix]==0,1,0))
cox_model <- coxph(survival_object ~ redcap$Gender[ix] + redcap$mucinous[ix] + redcap$Grade[ix] + redcap$LVI[ix] + redcap$PNI[ix] + redcap$stage_num[ix] + redcap$pMMR[ix] + redcap$APC[ix] + redcap$KRAS[ix] + redcap$p53[ix] +
                     redcap$BRAF[ix] + redcap$PIK3CA[ix] + redcap$tmb[ix])

# Extract the coefficients from the Cox model
coefficients <- cox_model$coefficients
hr <- exp(coefficients)
hr <- data.table(
  variable = names(coefficients),
  HR = hr,
  lower = exp(as.data.table(confint(cox_model, level = 0.95))$`2.5 %`),
  upper = exp(as.data.table(confint(cox_model, level = 0.95))$`97.5 %`)
)
hr$variable <- factor(hr$variable, levels = hr$variable[order(-hr$HR)])

# Create the forest plot
g <- ggplot(
  data = hr,
  aes(x = variable, y = HR, ymin = lower, ymax = upper)) +
  geom_pointrange(size = 0.8) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  coord_flip(ylim=c(0,10)) +
  xlab("Covariate") +
  ylab("Hazard Ratio") +
  theme_jw()
```

```{r cd3-by-tissue}
# Reshape data to long format
rr_long <- melt(rr, id.vars = "pMMR", measure.vars = c("CD3_200r", "CD4_200r","CD8_200r"), variable.name = "Metric", value.name = "Value")
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]
t.test(rr[pMMR=="pMMR", CD3_200r], rr[pMMR=="dMMR", CD3_200r]) # p = 0.02745
t.test(rr[pMMR=="pMMR", CD4_200r], rr[pMMR=="dMMR", CD4_200r]) # p = 0.4261
t.test(rr[pMMR=="pMMR", CD8_200r], rr[pMMR=="dMMR", CD8_200r]) # p = 0.01863
wilcox.test(rr[pMMR=="pMMR", CD3_200r], rr[pMMR=="dMMR", CD3_200r]) # p = 0.004448
wilcox.test(rr[pMMR=="pMMR", CD4_200r], rr[pMMR=="dMMR", CD4_200r]) # p = 0.4273
wilcox.test(rr[pMMR=="pMMR", CD8_200r], rr[pMMR=="dMMR", CD8_200r]) # p = 0.001122
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]

# Plot T cells subsets
g <- ggplot(rr_long, aes(x = pMMR, y = cells_per_mm2, fill = pMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Cells / mm2") +
  coord_cartesian(ylim=c(0,40000)) +
  scale_fill_manual(values = pMMR_colors) +
  facet_wrap(~ Metric) +  # Separate panel for each y variable
  theme_jw()

# Plot B and PD1 subsets
rr_long <- melt(rr, id.vars = "pMMR", measure.vars = c("CD20_200r", "PD1_200r","PD_L1_200r"), variable.name = "Metric", value.name = "Value")
wilcox.test(rr[pMMR=="pMMR", CD20_200r], rr[pMMR=="dMMR", CD20_200r]) # p = 0.06399
wilcox.test(rr[pMMR=="pMMR", PD1_200r], rr[pMMR=="dMMR", PD1_200r]) # p = 0.09163
wilcox.test(rr[pMMR=="pMMR",PD_L1_200r], rr[pMMR=="dMMR", PD_L1_200r]) # p = 0.02668
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]
g <- ggplot(rr_long, aes(x = pMMR, y = cells_per_mm2, fill = pMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Cells / mm2") +
  coord_cartesian(ylim=c(0,20000)) + 
  scale_fill_manual(values = pMMR_colors) +
  facet_wrap(~ Metric) +  # Separate panel for each y variable
  theme_jw()

# Plot innate cells subsets
rr_long <- melt(rr, id.vars = "pMMR", measure.vars = c("CD31_200r", "CD68_200r","CD163_200r"), variable.name = "Metric", value.name = "Value")
wilcox.test(rr[pMMR=="pMMR", CD31_200r], rr[pMMR=="dMMR", CD31_200r]) # p = 0.921
wilcox.test(rr[pMMR=="pMMR", CD68_200r], rr[pMMR=="dMMR", CD68_200r]) # p = 0.2608
wilcox.test(rr[pMMR=="pMMR", CD163_200r], rr[pMMR=="dMMR", CD163_200r]) # p = 0.2678
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]
g <- ggplot(rr_long, aes(x = pMMR, y = cells_per_mm2, fill = pMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Cells / mm2") +
  scale_fill_manual(values = pMMR_colors) +
  facet_wrap(~ Metric) +  # Separate panel for each y variable
  theme_jw()
```

```{r CD8_200r-distribution}
## CD8
setkey(rr, CD8_200r)
cd8_levels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=cd8_levels)]
g <- ggplot(rr, aes(x=Slide_ID, y=CD8_200r, fill=pMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw()

## CD3 count
rr[, ratio := panckcd3_200r]
setkey(rr, ratio)
clevels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=clevels)]
g <- ggplot(rr, aes(x=Slide_ID, y=ratio, fill=pMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw()

## CD3
setkey(rr, CD3_200r)
cd3_levels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=cd3_levels)]
g <- ggplot(rr, aes(x=Slide_ID, y=CD3_200r, fill=pMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw()
```

```{r TIL-vs-CD3}
rr[, cells_per_mm2 := CD45_200r * 1e6 / (1000^2 * 0.325^2)]
rr[, TIL := factor(TIL, levels=c("absent","mild","moderate","marked"))]
g <- ggplot(rr[!is.na(TIL)], aes(x = TIL, y = cells_per_mm2)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  ylab("CD45+ cells/mm2") +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  theme_jw()
wilcox.test(rr[TIL=="absent", CD45_200r], rr[TIL=="marked", CD45_200r])
wilcox.test(rr[TIL=="absent", CD45_200r], rr[TIL=="marked", CD45_200r])
```

```{r gene-mutation-enrichment-tipmmr}
## bar chart on pMMR, tipMMR, dMMR on Mutations
rrm <- melt(rr, id.vars = "tipMMR", measure.vars = c("BRAF", "APC", "CTNNB1", "KRAS", "p53","PIK3CA"), variable.name="Gene")
result <- rrm[, .(n = .N, mut = sum(value == 1, na.rm=TRUE)), by = .(tipMMR, Gene)]
result[, SE := sqrt((mut/n) * (1 - mut/n) / n)]
result[, lower_limit := mut/n - 1.96*SE]
result$lower_limit[result$lower_limit < 0] <- 0

fisher.test(matrix(c(sum(rr[tipMMR=="tipMMR", .(BRAF)]), rr[tipMMR=="tipMMR",.N],
  sum(rr[tipMMR=="pMMR", .(BRAF)], na.rm=TRUE), rr[tipMMR=="pMMR", .N]), nrow=2, ncol=2))
fisher.test(matrix(c(sum(rr[tipMMR=="tipMMR", .(APC)]), rr[tipMMR=="tipMMR",.N],
  sum(rr[tipMMR=="pMMR", .(APC)], na.rm=TRUE), rr[tipMMR=="pMMR", .N]), nrow=2, ncol=2))
fisher.test(matrix(c(sum(rr[tipMMR=="tipMMR", .(CTNNB1)]), rr[tipMMR=="tipMMR",.N],
  sum(rr[tipMMR=="pMMR", .(CTNNB1)], na.rm=TRUE), rr[tipMMR=="pMMR", .N]), nrow=2, ncol=2))

g <- ggplot(result, aes(x=Gene, fill=tipMMR, y=mut/n)) + 
  geom_bar(stat="identity", position="dodge", color="black") + 
  theme_jw() + scale_fill_manual(values=pMMR_colors) +
  ylab("Fraction of samples with mutation") +
  geom_errorbar(aes(ymin=lower_limit, ymax=mut/n + 1.96*SE), width=0.25, position=position_dodge(0.9))
save_pdf(g, "tipMMR_gene_bars.pdf", width=4.5,height=2)

## bar chart on pMMR, tipMMR, dMMR on Grade, Mucionus, LVI, PNI etc
rrm <- melt(rr, id.vars = "tipMMR", measure.vars = c("mucinous", "Grade", "LVI","PNI"), variable.name="Variable")
rrm[Variable=="Grade", value := as.integer(value=="High")]
result <- rrm[!is.na(value), .(n = .N, mut = sum(value == 1, na.rm=TRUE)), by = .(tipMMR, Variable)]
result[, SE := sqrt((mut/n) * (1 - mut/n) / n)]
result[, lower_limit := mut/n - 1.96*SE]
result$lower_limit[result$lower_limit < 0] <- 0

g <- ggplot(result, aes(x=Variable, fill=tipMMR, y=mut/n)) + 
  geom_bar(stat="identity", position="dodge", color="black") + 
  theme_jw() + scale_fill_manual(values=pMMR_colors) +
  ylab("Fraction of samples with feature") +
  geom_errorbar(aes(ymin=lower_limit, ymax=mut/n + 1.96*SE), width=0.25, position=position_dodge(0.9))
save_pdf(g, "tipMMR_hist_bars.pdf", width=3,height=2)

# age
g <- ggplot(rr, aes(x = tipMMR, y = Age, fill = tipMMR)) +
  geom_boxplot(alpha = 1, width=0.8, outlier.shape=NA) +  # Boxplot in the background with some transparency
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 1, shape=20) +  # Scatter plot with jitter
  labs(y = "Age") +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "tipMMR_age_box.pdf", width=3,height=2)

t.test(rr[tipMMR=="tipMMR", Age], rr[tipMMR=="dMMR", Age])
t.test(rr[tipMMR=="dMMR", Age], rr[tipMMR=="pMMR", Age])

# location
rrm <- melt(rr, id.vars = "tipMMR", measure.vars = c("side"), variable.name="side")
result <- rr[, .(SideCount = .N), by = .(tipMMR, side)][, N := sum(SideCount), by = tipMMR]
result <- rbind(result, data.table(tipMMR="dMMR",side="Rectal",SideCount=0, N=9))

result[, SE := sqrt((SideCount/N) * (1 - SideCount/N) / N)]
result[, lower_limit := SideCount/N - 1.96*SE]
result$lower_limit[result$lower_limit < 0] <- 0

g <- ggplot(result, aes(x=side, fill=tipMMR, y=SideCount/N)) + 
  geom_bar(stat="identity", position="dodge", color="black") + 
  theme_jw() + scale_fill_manual(values=pMMR_colors) +
  ylab("Fraction of samples with feature") +
  geom_errorbar(aes(ymin=lower_limit, ymax=SideCount/N + 1.96*SE), width=0.25, position=position_dodge(0.9))
save_pdf(g, "tipMMR_side_bars.pdf", width=3,height=2)

# gender bar chart on pMMR, tipMMR, dMMR on Mutations
# Calculating number of males and females, and the male-to-female ratio
result <- rrm[, .(n = .N, mut = sum(value == "M", na.rm=TRUE), females = sum(value != "M", na.rm=TRUE)), by = .(tipMMR)]
result[, ratio := mut/females]
result[, deviation := ratio - 1]

# Plotting the deviation from a ratio of 1 using horizontal bars
g <- ggplot(result, aes(y=tipMMR, x=deviation, fill=tipMMR)) + 
  geom_bar(stat="identity", position="dodge", color="black") + 
  scale_fill_manual(values=pMMR_colors) +
  #xlab("Deviation from Male-to-Female Ratio of 1 (Right indicates male predominance)") +
  geom_vline(xintercept=0, linetype="dashed") +  # Add a vertical dashed line at 0 for reference
  theme_jw() + 
  scale_x_continuous(name="M:F ratio", breaks=seq(-0.5, 0.5, by=0.25), labels=seq(0.5, 1.5, by=0.25))
save_pdf(g,"tipMMR_gender_bars.pdf", width=3, height=1)
```

```{r cd3-stage}
rr_long <- melt(rr, id.vars = c("tipMMR","stage_num"), measure.vars = c("CD3_200r"), variable.name = "Metric", value.name = "Value")
g <- ggplot(rr_long, aes(x=as.factor(stage_num), y = Value* 1e6 / (1000^2 * 0.325^2))) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA,notch=FALSE) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, shape=16) +
  labs(y = "Cells / mm2") +
  scale_y_log10()+
  scale_x_discrete(labels =c("I","II","III","IV")) +
  scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(axis.title.x = element_blank())
save_pdf(g, "stage_CD3_boxplot.pdf", width=3,height=3)
```

```{r checkpoint}
## PD1
setkey(rr, PD1_200r)
pd1_levels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=pd1_levels)]
g <- ggplot(rr, aes(x=Slide_ID, y=PD1_200r, fill=tipMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw() + scale_y_log10()
save_pdf(g, "pd1_waterfall.pdf", width=6, height=6)

# PD-L1
setkey(rr, PD_L1_200r)
pdl1_levels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=pdl1_levels)]
g <- ggplot(rr, aes(x=Slide_ID, y=PD_L1_200r, fill=tipMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw() + scale_y_log10()
save_pdf(g, "pdl1_waterfall.pdf", width=6, height=6)

# CD45RO
setkey(rr, CD45RO_200r)
plevels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=plevels)]
g <- ggplot(rr, aes(x=Slide_ID, y=CD45RO_200r, fill=tipMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw() + scale_y_log10()
p = ttest_pairs(rr, "tipMMR","CD45RO_200r")
#save_pdf(g, "pdl1_waterfall.pdf", width=6, height=6)

# Pan-CK -- PD-L1
setkey(rr, PanCKpPDL1_200r)
plevels <- rr$Slide_ID
rr[, Slide_ID := factor(Slide_ID, levels=plevels)]
g <- ggplot(rr, aes(x=Slide_ID, y=PanCKpPDL1_200r, fill=tipMMR)) + 
  geom_bar(stat="identity")+
  coord_flip() +
  scale_fill_manual(values=pMMR_colors) +
  theme_jw() + scale_y_log10()
save_pdf(g, "PanCKpPDL1_200r_waterfall.pdf", width=6, height=6)

# double-positive PD-L1 ratios
rr[, pdl1_div_cd168_200r := PD_L1_200r/CD163_200r]
rr[, pdl1_div_panCK_200r := PD_L1_200r/PanCK_200r]
rr_long <- melt(rr, id.vars = "tipMMR", measure.vars = c("pdl1_div_cd168_200r", "pdl1_div_panCK_200r"), variable.name = "Metric", value.name = "Value")
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]
g <- ggplot(rr_long, aes(x = tipMMR, y = cells_per_mm2, fill = tipMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Cells / mm2") +
  scale_fill_manual(values = pMMR_colors) +
  facet_wrap(~ Metric) +
  theme_jw()

# plot ratio of PDL1+ macrophage to tumor
rr[, ab := CD163pPDL1_200r / PanCKpPDL1_200r]
g <- ggplot(rr, aes(x = tipMMR, y = ab, fill = tipMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "PD-L1+ m0 / PD-L1+ Tumor") +
  scale_y_log10()+
  scale_fill_manual(values = pMMR_colors) +
  theme_jw()
save_pdf(g, "m0_tumor_pdl1_ratio.pdf", width=3, height=3)

rr_long <- melt(rr, id.vars = "tipMMR", measure.vars = c("PD1_200l", "PD_L1_200l", "CD45RO_200l", "PanCKpPDL1_200lg","CD163pPDL1_200lg", "ab"), variable.name = "Metric", value.name = "Value")
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]
pd1 = ttest_pairs(rr, "tipMMR","PD1_200r")
pdl1 = ttest_pairs(rr, "tipMMR","PD_L1_200r")

# Plot PD1/PDL1 
g <- ggplot(rr_long, aes(x = tipMMR, y = cells_per_mm2, fill = tipMMR)) +
  geom_boxplot(alpha = 0.5, width=0.8, outlier.shape=NA) +
  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Cells / mm2") +
  scale_y_log10()+
  scale_fill_manual(values = pMMR_colors) +
  facet_wrap(~ Metric) +
  theme_jw()
save_pdf(g, "pd1_pdl1_cd45ro_boxplot_tip.pdf", width=6,height=3)
```

```{r dbscan}
f <- data.table::fread(cmd="cysift view ~/Sorger/projects/orion/orion_1_74/chain/LSP10353.dbscan.cys")
fplot <- f[sample(.N,1e5), .(V5, V6,V217)][, cluster := ifelse(V217 > 0, "tumor","stroma")]
g <- ggplot(fplot, aes(x=V5, y=V6, color=cluster)) + geom_point(size=0.1, shape=20) + theme_jw() + scale_color_manual(values=c(tumor="blue",stroma="red"))
save_pdf(g, "dbtest.pdf", width=15, height=15)
```

```{r margins-raw-count}



# Example usage:

read_data_for_margin <- function(f, margin_type, a_value, n_value) {
  
  tmpfile <- paste0("/tmp/", generate_random_string(8))
  
    cd163pdl1_cmd <- paste("cysift filter", ifelse(!is.null(n_value), paste("-N", n_value), ""), ifelse(!is.null(a_value), paste("-A", a_value), ""), "-a 10240 -T", f, tmpfile, "&& cysift count", tmpfile)
    cd163pdl1 <- fread(cmd=cd163pdl1_cmd)$V1

    panckpdl1_cmd <- paste("cysift filter", ifelse(!is.null(n_value), paste("-N", n_value), ""), ifelse(!is.null(a_value), paste("-A", a_value), ""), "-a 133120 -T", f, tmpfile, "&& cysift count", tmpfile)
    panckpdl1 <- fread(cmd=panckpdl1_cmd)$V1

    allcells_cmd <- paste("cysift filter", ifelse(!is.null(n_value), paste("-N", n_value), ""), ifelse(!is.null(a_value), paste("-A", a_value), ""), "-T", f, tmpfile, "&& cysift count", tmpfile)
    allcells <- fread(cmd=allcells_cmd)$V1
    
    panck_allcells_cmd <- paste("cysift filter -a 131072", ifelse(!is.null(n_value), paste("-N", n_value), ""), ifelse(!is.null(a_value), paste("-A", a_value), ""), "-T", f, tmpfile, "&& cysift count", tmpfile)
    panck <- fread(cmd=panck_allcells_cmd)$V1
    
       cd163_allcells_cmd <- paste("cysift filter -a 8192", ifelse(!is.null(n_value), paste("-N", n_value), ""), ifelse(!is.null(a_value), paste("-A", a_value), ""), "-T", f, tmpfile, "&& cysift count", tmpfile)
    cd163 <- fread(cmd=cd163_allcells_cmd)$V1

    dt <- data.table(Slide_ID = sub("^(LSP[0-9]+).*", "\\1", basename(f)), 
                     cd163pdl1=cd163pdl1, 
                     panckpdl1=panckpdl1,
                     panck=panck,
                     cd163=cd163,
                     margin=margin_type, 
                     allcells=allcells)
    
    file.remove(tmpfile)
    return(dt)
}

files <- list.files(path = "~/Sorger/projects/orion/orion_1_74/margin/", full.names = TRUE)
files <- files[grepl("cys$", files)]
header <- header_read(files[1])

system.time(dtt <- parallel::mclapply(files, function(f) {
  
    cat(basename(f), "\n")
    dt_a4 <- read_data_for_margin(f, "A4", 4, NULL)
    dt_stroma_margin <- read_data_for_margin(f, "stroma_margin", 4, 1)
    dt_tumor_core <- read_data_for_margin(f, "tumor_core", 1, 4)
    dt_stroma_core <- read_data_for_margin(f, "stroma_core", NULL, 5)

    return(rbind(dt_a4, dt_tumor_core, dt_stroma_core, dt_stroma_margin))
}, mc.cores=8))

dtr <- rbindlist(dtt)
dtr[, cd163_frac := cd163pdl1 / allcells]
dtr[, panck_frac := panckpdl1 / allcells]
dtr[, pdl1_ratio := cd163pdl1 / panckpdl1]

ratios <- dtr[margin == "stroma_margin", .(Slide_ID, stroma_cd163pdl1 = cd163pdl1)][
  dtr, on = .(Slide_ID)][
    margin == "tumor_core", .(Slide_ID, cd163pdl1_ratio = stroma_cd163pdl1/cd163pdl1)]


# Merge the ratio back onto the original data.table
dtr <- merge(dtr, ratios, by = "Slide_ID", all.x = TRUE)

rr <- merge(data.table::copy(redcap), dtr, by = "Slide_ID", all.x = TRUE)
hard_coded_tip <- c("LSP14418", "LSP14398", "LSP14423", "LSP14438", "LSP14393", "LSP14403", "LSP14458", "LSP10771", "LSP14388", "LSP14468", "LSP14483", "LSP10388", "LSP14448")
rr[, tipMMR := factor(ifelse(Slide_ID %in% hard_coded_tip, ifelse(pMMR=="dMMR","dMMR","tipMMR"), as.character(pMMR)))]
  #saveRDS(dtr, "~/Sorger/cache/margin_pdl1.rds", compress=FALSE)
  
aa <- rr[, .(Slide_ID, tipMMR,cd163_frac, margin, cd163pdl1_ratio, panck_frac)][margin=="stroma_margin"]
setkey(aa, panck_frac)
clevels <- aa$Slide_ID
aa[,Slide_ID := factor(Slide_ID, levels=clevels)]
g <- ggplot(aa, aes(x=Slide_ID, y=panck_frac, fill=tipMMR)) + 
geom_bar(stat="identity")+
coord_flip() +
scale_fill_manual(values=pMMR_colors) + 
  theme_jw()

rr_long <- melt(rr, id.vars = c("tipMMR","margin"), measure.vars = c("pdl1_ratio", "panck_frac","cd163_frac"),
                variable.name = "Metric", value.name = "Value")
rr_long[, Metric_margin := interaction(Metric, margin, sep = " - ")]
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]

g <- ggplot(rr_long, aes(x = tipMMR, y = cells_per_mm2, fill = margin)) +
    geom_boxplot(alpha = 0.4, width=0.8, outlier.shape=NA) +
    #geom_jitter(aes(color=margin), size = 1, alpha = 0.7, shape=20) +
    labs(y = "Cells / mm2") +
    scale_y_log10() + 
    #scale_fill_manual(values = pMMR_colors) +
    facet_wrap(~ Metric) + theme_jw()
  
```

```{r margins}
rr_long <- melt(rr, id.vars = c("tipMMR","margin"), measure.vars = c("PanCKpPDL1_200lg","CD163pPDL1_200lg"),
                variable.name = "Metric", value.name = "Value")

rr_long[, Metric_margin := interaction(Metric, margin, sep = " - ")]
rr_long[, cells_per_mm2 := Value * 1e6 / (1000^2 * 0.325^2)]

g <- ggplot(rr_long, aes(x = tipMMR, y = cells_per_mm2, fill = margin)) +
  geom_boxplot(alpha = 0.4, width=0.8, outlier.shape=NA) +
  #geom_jitter(aes(color=margin), size = 1, alpha = 0.7, shape=20) +
  labs(y = "Cells / mm2") +
  scale_y_log10() + 
  #scale_fill_manual(values = pMMR_colors) +
  facet_wrap(~ Metric) + theme_jw()
save_pdf(g, "margin_compare_tcell_boxplot.pdf", width=6, height=3)
```

```{r histogram_cd3}
files <- list.files(path = "~/Sorger/projects/orion/orion_1_74/cut/", full.names = TRUE)
files <- files[grepl("cut$", files)]

# read all the data as the means within the tumor compartment
dtt <- lapply(files, function(f) {
  cat(basename(f), "\n")
  dt <- fread(cmd=paste("cysift cut -x CD3_200r",f,"- | cysift view -"))
  dt <- fread(f)
  
  setnames(dt, paste0("V",seq(7)), c("sample","cell","cflag","pflag","x","y", "cd3"))
  dt[, CD3p := bitwAnd(pflag, 4096) > 0]
  dt[, CD4p := bitwAnd(pflag, 64) > 0]
  dt[, CD8p := bitwAnd(pflag, 256) > 0]
  dt[, PanCKp := bitwAnd(pflag, 131072) > 0]
  #dt[, value := ifelse(bitwAnd(pflag, 4096) > 0, ifelse(bitwAnd(cflag, 4) > 0, "3T", "3S"), ifelse(bitwAnd(cflag, 4) > 0, "T","S"))]
  dt[, c("cell","cflag","pflag","x","y") := NULL]
  return(dt)
})
jaccard <- sapply(dtt, function(x) { x[, sum(CD3p & !CD8p & !CD4p) / (sum(CD3p))]})
names(jaccard) <- paste0("LSP",sapply(dtt, function(x) x$sample[1]))
dtj <- data.table(jaccard = jaccard, Slide_ID = names(jaccard))
ab <- merge(dtj[!Slide_ID %in% c("LSP10452")], rr[margin=="core1"])
g <- ggplot(ab, aes(x = tipMMR, y = jaccard, fill = tipMMR)) +
  geom_boxplot(alpha = 1, width=0.8, outlier.shape=NA) + 
  geom_jitter(position = position_jitter(width = 0.2), size = 3, alpha = 1, shape=20) +  labs(y = "CD3pCD8nCD4n/CD3p") + scale_fill_manual(values = pMMR_colors) +
  theme_jw() + theme(legend.position = "none")
save_pdf(g, "cd3cd4ncd8n_percent.pdf", width=3,height=3)

dtr <- rbindlist(dtt)
means <- dtr[(value == "T" | value == "3T"), .(mean_cd3 = mean(cd3)), by = .(sample)]
g <- ggplot(dtr[(value == "T" | value == "3T")], aes(x=cd3, fill=value)) + geom_histogram(position= "dodge", binwidth=50) + theme_jw() + coord_cartesian(xlim=c(0, 7000)) + 
  facet_wrap(~ sample) + geom_vline(data = means, aes(xintercept = mean_cd3), color = "red")
save_pdf(g, "cd3_200r_histogram_facet.pdf", width=20, height=20)
```

```{r jaccard}

files <- list.files(path = "~/Sorger/projects/orion/orion_1_74/pearson/", full.names = TRUE)
files <- files[grepl("pearson$", files)]

col_range <- colorRampPalette(c("darkblue", "white", "darkred"))(200)

dtt <- lapply(files, function(f) {
  cat(basename(f), "\n")
  dt <- fread(f)
  
  bl <- c("Hoechst", "Argo550","AF1")
  dt <- dt[!V1 %in% bl & !V2 %in% bl]
  
  # Visualize using ggplot2
  g <- ggplot(data = dt, aes(x = V1, y = V2)) +
  geom_tile(aes(fill = V3), color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), name="Correlation") +
  #geom_text(aes(label = sprintf("%.2f", value)), vjust = 1) +
  theme_jw() + ggtitle(sub("\\..*$", "", basename(f))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), 
        axis.title.x = element_blank(), axis.title.y = element_blank(), 
        legend.position = "none")
  
 # Create a square matrix of dimensions equal to unique values of V1 and V2
labels <- unique(c(dt$V1, dt$V2))
mat <- matrix(0, nrow=length(labels), ncol=length(labels))
rownames(mat) <- labels
colnames(mat) <- labels

# Fill the matrix
for (i in 1:nrow(dt)) {
  mat[dt$V1[i], dt$V2[i]] <- dt$V3[i]
  mat[dt$V2[i], dt$V1[i]] <- dt$V3[i]  # since the relationship is symmetric
}
  
  return(list(g=g, mat=mat, name=sub("\\..*$", "", basename(f))))
})
save_pdf(gridExtra::grid.arrange(grobs = lapply(dtt, function(x) x$g)), "pearson_facet.pdf", width=30, height=30)

##### NON PARALLEL
# Calculate pairwise Mantel tests
n <- length(dtt)
results <- matrix(NA, n, n)
rownames(results) <- names(dtt)
colnames(results) <- names(dtt)

for (i in 1:(n-1)) {
  cat(i,"\n")
  for (j in (i+1):n) {
    test <- mantel(dtt[[i]]$mat, dtt[[j]]$mat, method = "pearson", permutations = 999)
    results[i, j] <- test$statistic
    results[j, i] <- test$statistic
  }
}
##########

compute_mantel <- function(pair) {
  i <- pair[1]
  j <- pair[2]
  
  test <- mantel(dtt[[i]]$mat, dtt[[j]]$mat, method = "pearson", permutations = 999)
  return(list(i = i, j = j, statistic = test$statistic))
}

# Create a list of all pairs of indices
pairs <- list()
for (i in 1:(n-1)) {
  for (j in (i+1):n) {
    pairs <- c(pairs, list(c(i, j)))
  }
}

# Determine the number of cores to use; usually one less than all available cores
num_cores <- detectCores() - 1
system.time(results_list <- mclapply(pairs, compute_mantel, mc.cores = num_cores))

# extract into results matrix
results <- matrix(NA, n, n)
rownames(results) <- sapply(dtt, function(x) x$name)
colnames(results) <- sapply(dtt, function(x) x$name)
for (res in results_list) {
  results[res$i, res$j] <- res$statistic
  results[res$j, res$i] <- res$statistic
}

# Plot Mantel similarity matrix
df_results <- as.data.table(melt(results[!rownames(results) %in% hard_coded_tip, !colnames(results) %in% hard_coded_tip]))
colnames(df_results) <- c("Matrix1", "Matrix2", "Mantel_r")
g <- ggplot(df_results, aes(Matrix1, Matrix2, fill = Mantel_r)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(title = "Mantel Test Similarity Matrix", fill = "Mantel r")

library(ComplexUpset)

# 1. Calculate the distance matrix.
# Given that the results are correlation coefficients (from Mantel test),
# we can calculate the distance as (1 - correlation coefficient).
# This makes perfect correlations have a distance of 0 and no correlation a distance of 1.
dist_matrix <- 1 - abs(results[!rownames(results) %in% hard_coded_tip, !colnames(results) %in% hard_coded_tip])

# 2. Perform hierarchical clustering
clustering <- hclust(as.dist(dist_matrix))
dendrogram <- as.dendrogram(clustering)

# 3. Rearrange the results matrix based on clustering order
order <- order.dendrogram(dendrogram)
clustered_results <- results[order, order]

# 4. Plot the clustered matrix
df_clustered_results <- melt(clustered_results)
colnames(df_clustered_results) <- c("Matrix1", "Matrix2", "Mantel_r")

g <- ggplot(df_clustered_results, aes(Matrix1, Matrix2, fill = Mantel_r)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Clustered Mantel Test Similarity Matrix", fill = "Mantel r")

# Using heatmap.2 for visualization with dendrogram
save_pdf(heatmap.2(clustered_results, 
          main = "Clustered Mantel Test Similarity Matrix", 
          notecol="black",      # change font color of cell labels to black
          density.info="none",  # turns off density plot inside color legend
          trace="none",         # turns off trace lines inside the heat map
          margins =c(8,9),      # widens margins around plot
          dendrogram = "row",   # only draw a row dendrogram
          col = colorRampPalette(c("blue", "white", "red"))(25),
          Colv = NULL),          # keep the column order as it is
         "mantel_dendrogram_pearson_nontip.pdf", width=20, height=20)
```

```{r contour-plots}
library(ggplot2)

files <- list.files(path = "~/Sorger/projects/orion/orion_1_74/margin/", full.names = TRUE)
files <- files[grepl("cys$", files)]

#num_cells <- sum(sapply(files, function(f) {
#  fread(cmd=paste("cysift count", f))$V1
#}))

header <- header_read(files[1])

bw = 100

# set common levels for cd3
dt_max <- fread(cmd=paste("cysift clean -m -M",files[57], "- | cysift view -"))
dt_min <- fread(cmd=paste("cysift clean -m -M",files[5], "- | cysift view -"))
kde_result_max <- MASS::kde2d(dt_max[bitwAnd(V4, 4096) > 0,V5], dt_max[bitwAnd(V4, 4096) > 0, V6], n=bw)
kde_result_min <- MASS::kde2d(dt_min[bitwAnd(V4, 4096) > 0,V5], dt_min[bitwAnd(V4, 4096) > 0, V6], n=bw)
common_levels_cd3 <- seq(min(kde_result_min$z), max(kde_result_max$z), length.out = 30)[seq(2,30)]

# set common levels for tumor
dt_max <- fread(cmd=paste("cysift clean -m -M",files[1], "- | cysift view -"))
dt_min <- fread(cmd=paste("cysift clean -m -M",files[1], "- | cysift view -"))
kde_result_max <- MASS::kde2d(dt_max[bitwAnd(V3, 1) > 0,V5], dt_max[bitwAnd(V3, 1) > 0, V6], n=bw)
kde_result_min <- MASS::kde2d(dt_min[bitwAnd(V3, 1) > 0,V5], dt_min[bitwAnd(V3, 1) > 0, V6], n=bw)
common_levels_tumor <- seq(min(kde_result_min$z), max(kde_result_max$z), length.out = 30)[seq(2,30)]

# get all of the cd3_200 values
cd3 <- lapply(files, function(f) {
  cat(basename(f), "\n")
  dt <- fread(cmd=paste("cysift cut -x CD3_200r",f,"- | cysift view -"))
  return(dt$V7)
})
cd3a_function <- ecdf(unlist(cd3))


# get all of the cd3_200 / panck values
cd3pank <- lapply(files, function(f) {
  cat(basename(f), "\n")
  dt <- fread(cmd=paste("cysift cut -x CD3_200r,PanCK_200r",f,"/tmp/tmpr && cysift view /tmp/tmpr"))
  return(dt[V7 > 0 & V8 > 0, V8/V7]) # V7 is PanCK
})
cp_function <- ecdf(unlist(cd3pank))

# read all the data as the means within the tumor compartment
dtt <- lapply(files, function(f) {
  cat(basename(f), "\n")
  dt <- fread(cmd=paste("cysift cut -x PanCK_200l,CD3_200r",f,"- | cysift view -"))
  setnames(dt, paste0("V",seq(8)), c("sample","cell","cflag","pflag","x","y", "cd3","pk"))
  #setnames(dt, paste0("V",seq(7,ncol(dt))), header$id[header$tag_type %in% c("CA","MA")])
  dt[, Slide_ID := sub("^(LSP[0-9]+).*", "\\1", basename(f))]
  dt[, ratio := cd3/pk]
  dt[pk == 0, ratio := -1]
  dt[, ratio_z := cp_function(ratio)]
  dt[cd3==0, ratio_z := 0]
  #dt[, margin := "stroma_n5"]
  
  dt[, value := ifelse(bitwAnd(pflag, 4096) > 0, ifelse(bitwAnd(cflag, 4) > 0, "CD3", "CD3"), ifelse(bitwAnd(cflag, 4) > 0, "tumor","stroma"))]
  
  # CD3 KDE
 # kde_result <- MASS::kde2d(dt[value == "CD3",x], dt[value == "CD3",y], n = bw)
 # kde_df_cd3 <- as.data.table(expand.grid(x = kde_result$x, y = kde_result$y))
 # kde_df_cd3[, z := as.vector(kde_result$z)]
  
  # TUMOR KDE
  #kde_result <- MASS::kde2d(dt[value == "tumor",x], dt[value == "tumor",y], n = bw)
  #kde_df_tumor <- as.data.table(expand.grid(x = kde_result$x, y = kde_result$y))
  #kde_df_tumor[, z := as.vector(kde_result$z)]
  
  lim.low = 0
  lim.high = 10000
  dt[cd3 < lim.low,cd3 := lim.low]
  dt[cd3 > lim.high, cd3 := lim.high]

  #dt[, cd3value := cd3_function(cd3)]
  #dt[, ratio := ifelse(ratio > lim.high, lim.high, ratio)]
  
  g <- ggplot() +
    geom_point(data=dt[sample(.N, 1e5)], aes(x=x,y=y,color=cd3), 
               size=0.1) + 
    scale_color_gradient2(low = "#67a9cf", mid = "#f7f7f7", high = "#ef8a62", 
                          midpoint = lim.high/2, limits = c(lim.low, lim.high), 
                          guide = "colourbar", aesthetics = "color") +
   # geom_contour(data = kde_df_tumor, aes(x=x,y=y,z=z),color = "darkred", alpha = 0.5) + 
       #geom_contour(data = kde_df_cd3, aes(x=x,y=y,z=z),color = "black", alpha = 0.5, linewidth=0.3) + ggtitle(dt$Slide_ID[1]) + 
    theme_jw() +
    coord_fixed(ratio = 1)
  return(g)
})
ge <- gridExtra::grid.arrange(grobs = dtt, ncol = 10, nrow = 7)
save_pdf(gridExtra::grid.arrange(grobs = dtt, ncol = 10, nrow = 8), "kde_cd3.pdf", width=20, height=20)
```



